language: java

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

addons:

apt:

packages:
- oracle-java8-installer

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11
